db:
    driver: mysql
    host: localhost
    dbname: halfway
    user: myuser
    password: mypass

debug: false

exec_path: /www/halfway-dev/prog

# used to set specific_locations_only:, local_only
#main_scope: *
# TODO should be set per-perspective
main_title: The Halfway Library
max_favorites: 10

default_call_system: lc
#as_column
#with_incomplete
#divide_topics
#highlight_accessible
#minimum_publicity

default_z_servers:
    melvyl.cdlib.org:
        port: 210
        dbname: CDL90
        enabled: true
    z3950.loc.gov:
        port: 7090
        dbname: Voyager
        enabled: true
    catalog.library.cornell.edu:
        port: 7090
        dbname: VOYAGER
        enabled: true
    bobcat.nyu.edu:
        port: 210
        dbname: advance
        enabled: false
    library.ox.ac.uk:
        port: 210
        dbname: advance
        enabled: false
    prodorbis.library.yale.edu:
        port: 7090
        dbname: voyager
        enabled: false
    www.loc.gov:
        port: NULL
        dbname: NULL
        enabled: false
    www.amazon.com:
        port: NULL
        dbname: NULL
        enabled: false
    Z3950cat.bl.uk:
        port: 9909
        dbname: BLAC
        enabled: false
